---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: version
  image: syncloud/build-deps-arm
  commands:
  - "echo $(date +%y%m%d)$DRONE_BUILD_NUMBER > version"
  - "echo nextcloud > name"
  - "echo arm$DRONE_BRANCH > domain"

- name: build
  image: syncloud/build-deps-arm
  commands:
  - NAME=$(cat name)
  - VERSION=$(cat version)
  - ./build.sh $NAME $VERSION

- name: test-intergation
  image: syncloud/build-deps-arm
  commands:
  - pip2 install -r dev_requirements.txt
  - APP_ARCHIVE_PATH=$(realpath $(cat package.name))
  - DOMAIN=$(cat domain)
  - NAME=$(cat name)
  - cd integration
  - py.test -x -s verify.py --domain=$DOMAIN --app-archive-path=$APP_ARCHIVE_PATH --device-host=device --app=$NAME


- name: upload
  image: syncloud/build-deps-arm
  commands:
  - VERSION=$(cat version)
  - NAME=$(cat name)
  - PACKAGE=$(cat package.name)
  - pip2 install -r dev_requirements.txt
  - syncloud-upload.sh $NAME $DRONE_BRANCH $VERSION $PACKAGE
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY

- name: ci-artifact
  image: syncloud/build-deps-arm
  commands:
  - NAME=$(cat name)
  - PACKAGE=$(cat package.name)
  - pip2 install -r dev_requirements.txt
  - syncloud-upload-artifact.sh $NAME integration/log $DRONE_BUILD_NUMBER-$(dpkg --print-architecture)
  - syncloud-upload-artifact.sh $NAME integration/screenshot $DRONE_BUILD_NUMBER-$(dpkg --print-architecture)
  - syncloud-upload-artifact.sh $NAME $PACKAGE $DRONE_BUILD_NUMBER-$(dpkg --print-architecture)
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
  when:
    status:
    - failure
    - success

services:
- name: device
  image: syncloud/systemd-arm
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev

volumes:
- name: dbus
  host:
    path: /var/run/dbus
- name: dev
  host:
    path: /dev
- name: shm
  temp: {}

---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: version
  image: syncloud/build-deps-amd64
  commands:
  - "echo $(date +%y%m%d)$DRONE_BUILD_NUMBER > version"
  - "echo nextcloud > name"
  - "echo amd64$DRONE_BRANCH > domain"

- name: build
  image: syncloud/build-deps-amd64
  commands:
  - NAME=$(cat name)
  - VERSION=$(cat version)
  - ./build.sh $NAME $VERSION

- name: test-intergation
  image: syncloud/build-deps-amd64
  commands:
  - pip2 install -r dev_requirements.txt
  - APP_ARCHIVE_PATH=$(realpath $(cat package.name))
  - DOMAIN=$(cat domain)
  - NAME=$(cat name)
  - cd integration
  - py.test -x -s verify.py --domain=$DOMAIN --app-archive-path=$APP_ARCHIVE_PATH --device-host=device --app=$NAME

- name: test-ui
  image: syncloud/build-deps-amd64
  commands:
  - pip2 install -r dev_requirements.txt
  - DOMAIN=$(cat domain)
  - NAME=$(cat name)
  - cd integration
  - "xvfb-run -l --server-args='-screen 0, 1024x4096x24' py.test -x -s test-ui.py --ui-mode=desktop --domain=$DOMAIN --device-host=device --app=$NAME"
  - "xvfb-run -l --server-args='-screen 0, 1024x4096x24' py.test -x -s test-ui.py --ui-mode=mobile --domain=$DOMAIN --device-host=device --app=$NAME"
  volumes:
  - name: shm
    path: /dev/shm

- name: upload
  image: syncloud/build-deps-amd64
  commands:
  - VERSION=$(cat version)
  - NAME=$(cat name)
  - PACKAGE=$(cat package.name)
  - pip2 install -r dev_requirements.txt
  - syncloud-upload.sh $NAME $DRONE_BRANCH $VERSION $PACKAGE
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY

- name: ci-artifact
  image: syncloud/build-deps-amd64
  commands:
  - NAME=$(cat name)
  - PACKAGE=$(cat package.name)
  - pip2 install -r dev_requirements.txt
  - syncloud-upload-artifact.sh $NAME integration/log $DRONE_BUILD_NUMBER-$(dpkg --print-architecture)
  - syncloud-upload-artifact.sh $NAME integration/screenshot $DRONE_BUILD_NUMBER-$(dpkg --print-architecture)
  - syncloud-upload-artifact.sh $NAME $PACKAGE $DRONE_BUILD_NUMBER-$(dpkg --print-architecture)
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
  when:
    status:
    - failure
    - success

services:
- name: device
  image: syncloud/systemd-amd64
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev

volumes:
- name: dbus
  host:
    path: /var/run/dbus
- name: dev
  host:
    path: /dev
- name: shm
  temp: {}

...
