platform: linux/${arch}

clone:
  git:
    image: syncloud/drone-git-${arch}
    depth: 50

pipeline:
  version:
    image: syncloud/build-deps-${arch}
    commands:
      - echo $(date +%y%m%d)$DRONE_BUILD_NUMBER > version
      
  build:
    image: syncloud/build-deps-${arch}
    commands:
      - VERSION=$(cat version)
      - ./build.sh $VERSION

  test:
    image: syncloud/build-deps-${arch}
    commands:
      - VERSION=$(cat version)
      - ./integration/test-docker.sh build-$(uname -m)-$DRONE_BRANCH device $(cat package.name) verify.py

  test-ui:
    image: syncloud/build-deps-${arch}
    commands:
      - VERSION=$(cat version)
      - ./integration/test-docker.sh build-$(uname -m)-$DRONE_BRANCH device $(cat package.name) test-ui.py
    when:
      platform: linux/amd64

  upload:
    image: syncloud/build-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - VERSION=$(cat version)
      - ./upload.sh $DRONE_BRANCH $VERSION

  ci-artifact:
    image: syncloud/build-deps-${arch}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./upload-artifact.sh integration/log $DRONE_BUILD_NUMBER-$(dpkg --print-architecture)
      - ./upload-artifact.sh integration/screenshot $DRONE_BUILD_NUMBER-$(dpkg --print-architecture)
    when:
      status: [ failure, success ] 

services:
  device:
    image: syncloud/systemd-${arch}
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
 
matrix:
  arch:
    - arm
    - amd64