#!/bin/bash -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../../../../.. && pwd )
LIBS=$(echo ${DIR}/lib/*linux*/)
LIBS=$LIBS:$(echo ${DIR}/usr/lib/*linux*)
exec ${DIR}/lib/*/ld-*.so --library-path $LIBS ${DIR}/usr/lib/postgresql/*/bin/pg_dump.bin "$@"
